[package]
name = "grazelang"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "graze"
path = "src/main.rs"

[dependencies]
logos = "0.16.1"
serde.workspace = true
serde_json.workspace = true
arcstr.workspace = true
regex = "1.13.1"
rand = "0.10.2"
rand_xoshiro = "0.8.1"
thiserror = "2.0.19"
grazelang_library_parser = { path = "../grazelang_library_parser" }
grazelang_types = { path = "../grazelang_types" }
md5 = "0.8.1"
zip = "8.6.0"
enum-assoc = "1.3.0"
clap = { version = "4.6.4", features = ["derive"] }
ryu-js = "1.0.3"
fast-float2 = "0.2.3"
num_enum = "0.7.6"
annotate-snippets = "0.12.16"
anstream = "1.0.0"
sha3.workspace = true
base16ct.workspace = true
toml.workspace = true

[features]
default = []
include_context_in_parse_errors = []
