[package]
name = "grazelang_library_parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
arcstr.workspace = true
syn = { version = "3.0.3", features = ["full", "extra-traits"] }
serde_json.workspace = true
serde.workspace = true
quote.workspace = true
grazelang_types = { path = "../grazelang_types" }
sha3.workspace = true
base16ct.workspace = true
proc-macro2 = "1.0.106"
toml.workspace = true
